import { userPhotoCards } from "./userPhotoCard.seed";

export const saleCards = [
  {
    id: "948ea1dc-8573-4882-a903-3ade06ddae7f",
    quantity: 1,
    price: 1000,
    status: "ON_SALE",
    exchangeDescription: "원하면 교환 가능",
    exchangeGrade: "COMMON",
    exchangeGenre: "Animal",
    sellerId: userPhotoCards[0].ownerId,
    photoCardId: userPhotoCards[0].photoCardId,
    userPhotoCardId: userPhotoCards[0].id,
  },
  {
    id: "f9c70082-ac71-40d9-bf20-4bc5a9fdc83b",
    quantity: 2,
    price: 3000,
    status: "ON_SALE",
    exchangeDescription: "B급 이상의 카드 교환 희망",
    exchangeGrade: "COMMON",
    exchangeGenre: "Nature",
    sellerId: userPhotoCards[1].ownerId,
    photoCardId: userPhotoCards[1].photoCardId,
    userPhotoCardId: userPhotoCards[1].id,
  },
  {
    id: "472ad68f-7c68-4753-887f-95935588369f",
    quantity: 1,
    price: 500,
    status: "ON_SALE",
    exchangeDescription: "C급도 가능합니다",
    exchangeGrade: "COMMON",
    exchangeGenre: "Abstract",
    sellerId: userPhotoCards[2].ownerId,
    photoCardId: userPhotoCards[2].photoCardId,
    userPhotoCardId: userPhotoCards[2].id,
  },
  {
    id: "ec7ffb1d-6924-476d-91f3-7257e6be72a0",
    quantity: 3,
    price: 2000,
    status: "ON_SALE",
    exchangeDescription: "가격 조정 가능",
    exchangeGrade: "COMMON",
    exchangeGenre: "Animal",
    sellerId: userPhotoCards[3].ownerId,
    photoCardId: userPhotoCards[3].photoCardId,
    userPhotoCardId: userPhotoCards[3].id,
  },
  {
    id: "68420376-45c7-4a17-ad98-9427e622c7e2",
    quantity: 2,
    price: 1500,
    status: "ON_SALE",
    exchangeDescription: "S급 동물 카드 교환 희망",
    exchangeGrade: "COMMON",
    exchangeGenre: "Animal",
    sellerId: userPhotoCards[4].ownerId,
    photoCardId: userPhotoCards[4].photoCardId,
    userPhotoCardId: userPhotoCards[4].id,
  },
  {
    id: "dba42a03-0046-4252-8997-477028ab8095",
    quantity: 1,
    price: 1200,
    status: "ON_SALE",
    exchangeDescription: "같은 장르 교환 선호",
    exchangeGrade: "COMMON",
    exchangeGenre: "Nature",
    sellerId: userPhotoCards[5].ownerId,
    photoCardId: userPhotoCards[5].photoCardId,
    userPhotoCardId: userPhotoCards[5].id,
  },
  {
    id: "b9d5815f-556f-44fb-9cb8-94835d54ab20",
    quantity: 2,
    price: 900,
    status: "ON_SALE",
    exchangeDescription: "등급 상관없음",
    exchangeGrade: "COMMON",
    exchangeGenre: "Cityscape",
    sellerId: userPhotoCards[6].ownerId,
    photoCardId: userPhotoCards[6].photoCardId,
    userPhotoCardId: userPhotoCards[6].id,
  },
  {
    id: "8a8f3c42-0ca9-4e7e-a4ed-d570905eab04",
    quantity: 1,
    price: 1800,
    status: "ON_SALE",
    exchangeDescription: "추가금 가능",
    exchangeGrade: "COMMON",
    exchangeGenre: "Abstract",
    sellerId: userPhotoCards[7].ownerId,
    photoCardId: userPhotoCards[7].photoCardId,
    userPhotoCardId: userPhotoCards[7].id,
  },
  {
    id: "7e4f3d78-7452-4be0-83cc-9e55e79dc06c",
    quantity: 4,
    price: 2200,
    status: "ON_SALE",
    exchangeDescription: "고급 카드 교환 환영",
    exchangeGrade: "COMMON",
    exchangeGenre: "Cityscape",
    sellerId: userPhotoCards[8].ownerId,
    photoCardId: userPhotoCards[8].photoCardId,
    userPhotoCardId: userPhotoCards[8].id,
  },
  {
    id: "723bcecd-a0cb-465d-a756-3af36f739ae5",
    quantity: 1,
    price: 700,
    status: "ON_SALE",
    exchangeDescription: "최저가 양도",
    exchangeGrade: "COMMON",
    exchangeGenre: "Animal",
    sellerId: userPhotoCards[9].ownerId,
    photoCardId: userPhotoCards[9].photoCardId,
    userPhotoCardId: userPhotoCards[9].id,
  },
  // 추가 20개 (총 30개)
  {
    id: "2db897f7-f75c-4bc4-8c0c-251242fa27b5",
    quantity: 2,
    price: 2000,
    status: "ON_SALE",
    exchangeDescription: "동일 장르 A급 이상만",
    exchangeGrade: "COMMON",
    exchangeGenre: "Nature",
    sellerId: userPhotoCards[10].ownerId,
    photoCardId: userPhotoCards[10].photoCardId,
    userPhotoCardId: userPhotoCards[10].id,
  },
  {
    id: "802bcfc0-8403-4e32-a1a2-a72d78a05570",
    quantity: 3,
    price: 2500,
    status: "ON_SALE",
    exchangeDescription: "B급이라도 가능",
    exchangeGrade: "COMMON",
    exchangeGenre: "Nature",
    sellerId: userPhotoCards[11].ownerId,
    photoCardId: userPhotoCards[11].photoCardId,
    userPhotoCardId: userPhotoCards[11].id,
  },
  {
    id: "02a67b08-5a6b-41b3-8ba7-08079247c9c2",
    quantity: 1,
    price: 400,
    status: "ON_SALE",
    exchangeDescription: "미개봉 카드와 교환",
    exchangeGrade: "COMMON",
    exchangeGenre: "Abstract",
    sellerId: userPhotoCards[12].ownerId,
    photoCardId: userPhotoCards[12].photoCardId,
    userPhotoCardId: userPhotoCards[12].id,
  },
  {
    id: "7def824a-d7b3-43ff-acfd-53e48211c82e",
    quantity: 1,
    price: 1500,
    status: "ON_SALE",
    exchangeDescription: "최대한 빨리 거래",
    exchangeGrade: "COMMON",
    exchangeGenre: "Animal",
    sellerId: userPhotoCards[13].ownerId,
    photoCardId: userPhotoCards[13].photoCardId,
    userPhotoCardId: userPhotoCards[13].id,
  },
  {
    id: "c41b3e8c-2a20-4e25-b9c1-bdf60f847f5d",
    quantity: 6,
    price: 2800,
    status: "ON_SALE",
    exchangeDescription: "특이 장르도 가능",
    exchangeGrade: "COMMON",
    exchangeGenre: "Abstract",
    sellerId: userPhotoCards[14].ownerId,
    photoCardId: userPhotoCards[14].photoCardId,
    userPhotoCardId: userPhotoCards[14].id,
  },
  {
    id: "b85d9bc3-4ca0-4d92-9cb1-4c909d2df58b",
    quantity: 2,
    price: 1300,
    status: "ON_SALE",
    exchangeDescription: "동물 장르 우대",
    exchangeGrade: "COMMON",
    exchangeGenre: "Animal",
    sellerId: userPhotoCards[15].ownerId,
    photoCardId: userPhotoCards[15].photoCardId,
    userPhotoCardId: userPhotoCards[15].id,
  },
  {
    id: "b2987c9b-9700-4d85-89ab-ce65ea0e6f8e",
    quantity: 1,
    price: 900,
    status: "ON_SALE",
    exchangeDescription: "구매/교환 모두 가능",
    exchangeGrade: "COMMON",
    exchangeGenre: "Nature",
    sellerId: userPhotoCards[16].ownerId,
    photoCardId: userPhotoCards[16].photoCardId,
    userPhotoCardId: userPhotoCards[16].id,
  },
  {
    id: "2bf7feca-5bea-4b63-8666-4b62c1ff58ae",
    quantity: 1,
    price: 700,
    status: "ON_SALE",
    exchangeDescription: "C급이면 충분",
    exchangeGrade: "RARE",
    exchangeGenre: "Animal",
    sellerId: userPhotoCards[17].ownerId,
    photoCardId: userPhotoCards[17].photoCardId,
    userPhotoCardId: userPhotoCards[17].id,
  },
  {
    id: "7f86c7ca-a47b-482d-88f7-cfb7c6449fc5",
    quantity: 2,
    price: 1800,
    status: "ON_SALE",
    exchangeDescription: "급처합니다",
    exchangeGrade: "RARE",
    exchangeGenre: "Cityscape",
    sellerId: userPhotoCards[18].ownerId,
    photoCardId: userPhotoCards[18].photoCardId,
    userPhotoCardId: userPhotoCards[18].id,
  },
  {
    id: "578e698f-b897-4b4e-83da-6a0fb82ff129",
    quantity: 7,
    price: 3200,
    status: "ON_SALE",
    exchangeDescription: "여러 장 교환 가능",
    exchangeGrade: "RARE",
    exchangeGenre: "Animal",
    sellerId: userPhotoCards[19].ownerId,
    photoCardId: userPhotoCards[19].photoCardId,
    userPhotoCardId: userPhotoCards[19].id,
  },
  {
    id: "449f5c91-0e0a-4952-a01b-235b6e88ed0b",
    quantity: 1,
    price: 600,
    status: "ON_SALE",
    exchangeDescription: "급처, 흥정 환영",
    exchangeGrade: "RARE",
    exchangeGenre: "Nature",
    sellerId: userPhotoCards[20].ownerId,
    photoCardId: userPhotoCards[20].photoCardId,
    userPhotoCardId: userPhotoCards[20].id,
  },
  {
    id: "3c3badf9-66d8-459f-976a-d365a354869c",
    quantity: 2,
    price: 950,
    status: "ON_SALE",
    exchangeDescription: "A급 이상만",
    exchangeGrade: "RARE",
    exchangeGenre: "Animal",
    sellerId: userPhotoCards[21].ownerId,
    photoCardId: userPhotoCards[21].photoCardId,
    userPhotoCardId: userPhotoCards[21].id,
  },
  {
    id: "4f55752c-adbb-4563-a7d4-91f1125456f3",
    quantity: 1,
    price: 1100,
    status: "ON_SALE",
    exchangeDescription: "네고 가능",
    exchangeGrade: "RARE",
    exchangeGenre: "Abstract",
    sellerId: userPhotoCards[22].ownerId,
    photoCardId: userPhotoCards[22].photoCardId,
    userPhotoCardId: userPhotoCards[22].id,
  },
  {
    id: "b63e3ff2-d877-4140-a8ec-0eae496155b7",
    quantity: 4,
    price: 2100,
    status: "ON_SALE",
    exchangeDescription: "동일 등급 교환 희망",
    exchangeGrade: "RARE",
    exchangeGenre: "Animal",
    sellerId: userPhotoCards[23].ownerId,
    photoCardId: userPhotoCards[23].photoCardId,
    userPhotoCardId: userPhotoCards[23].id,
  },
  {
    id: "606b0ee5-3d73-47c6-b869-a3f1d7719fa8",
    quantity: 2,
    price: 1300,
    status: "ON_SALE",
    exchangeDescription: "추가금 내겠습니다",
    exchangeGrade: "RARE",
    exchangeGenre: "Nature",
    sellerId: userPhotoCards[24].ownerId,
    photoCardId: userPhotoCards[24].photoCardId,
    userPhotoCardId: userPhotoCards[24].id,
  },
  {
    id: "838d87a9-e8e2-40f7-97d8-5a5b5126d6a2",
    quantity: 5,
    price: 2700,
    status: "ON_SALE",
    exchangeDescription: "등급 상관없이 OK",
    exchangeGrade: "SUPER_RARE",
    exchangeGenre: "Abstract",
    sellerId: userPhotoCards[25].ownerId,
    photoCardId: userPhotoCards[25].photoCardId,
    userPhotoCardId: userPhotoCards[25].id,
  },
  {
    id: "024eeb47-e6b9-44bf-a4f1-39434202d6aa",
    quantity: 1,
    price: 1000,
    status: "ON_SALE",
    exchangeDescription: "첫거래 환영",
    exchangeGrade: "SUPER_RARE",
    exchangeGenre: "Animal",
    sellerId: userPhotoCards[26].ownerId,
    photoCardId: userPhotoCards[26].photoCardId,
    userPhotoCardId: userPhotoCards[26].id,
  },
  {
    id: "5dfc8dcc-99df-464e-a2b5-b01bb724d85d",
    quantity: 2,
    price: 750,
    status: "ON_SALE",
    exchangeDescription: "B급 이하 환영",
    exchangeGrade: "SUPER_RARE",
    exchangeGenre: "Cityscape",
    sellerId: userPhotoCards[27].ownerId,
    photoCardId: userPhotoCards[27].photoCardId,
    userPhotoCardId: userPhotoCards[27].id,
  },
  {
    id: "65d90fe0-5e05-4e0c-a9a2-a0824446442f",
    quantity: 3,
    price: 1950,
    status: "ON_SALE",
    exchangeDescription: "동물/자연 좋아요",
    exchangeGrade: "SUPER_RARE",
    exchangeGenre: "Nature",
    sellerId: userPhotoCards[28].ownerId,
    photoCardId: userPhotoCards[28].photoCardId,
    userPhotoCardId: userPhotoCards[28].id,
  },
  {
    id: "1ceda18c-f393-4c69-ae2e-30cd9ed1f8db",
    quantity: 1,
    price: 1200,
    status: "ON_SALE",
    exchangeDescription: "원하시면 연락주세요",
    exchangeGrade: "LEGENDARY",
    exchangeGenre: "Animal",
    sellerId: userPhotoCards[29].ownerId,
    photoCardId: userPhotoCards[29].photoCardId,
    userPhotoCardId: userPhotoCards[29].id,
  },
];
